#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Fetch latest HA stable + beta versions from PyPI
VERSIONS=$(curl -s https://pypi.org/pypi/homeassistant/json | jq -r '.releases | keys | .[]')

# Latest major version release (x.y.0 only)
HA_MAJOR_VERSION=$(echo "$VERSIONS" | grep -Ev '[a-zA-Z]' | grep '\.0$' | sort -Vr | head -n1)
HA_STABLE_VERSION=$HA_MAJOR_VERSION
export HA_STABLE_VERSION

tox -e lint
